"""Turn the transcribed library into a list you can actually read.

`search.py` answers "where is this line?". This answers the other question:
"what is in this font at all?" -- one table per font, every spoken file with
its text, so you can skim a pack instead of listening to it file by file.

Uncertain transcriptions are marked rather than dropped. Whisper returns fluent
sentences for audio containing no speech, and the quote/font/boot/force families
are treated as speech by filename so that unusual real speech survives -- a
laugh, a growl, a droid chirp. That choice lets invented text through too, so
anything doubtful is flagged for the ear rather than deleted.

The output is deliberately NOT committed to this repository (see .gitignore):
it contains transcripts of copyrighted film dialogue and belongs on your machine.

USAGE
    python tools/report.py
    python tools/report.py --library sound-library.json --out sound-library.md
    python tools/report.py --font IWVader          # one font only
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

# Phrases Whisper falls back on when there is nothing to transcribe. They come
# from subtitle-heavy training data, and on a saber card they almost always mean
# "this file has no speech in it".
COMMON_HALLUCINATIONS = {
    "thank you", "thanks for watching", "you", "yeah", "bye", "okay",
    "subtitles by the amara org community", "please subscribe",
}


def normalise(text: str) -> str:
    return " ".join((text or "").lower().replace(",", " ").replace(".", " ").split())


def suspect_reason(entry: dict) -> str:
    """Why this transcription deserves a listen before you trust it, or ''."""
    text = normalise(entry.get("text", ""))
    no_speech = entry.get("no_speech_prob", 0.0)
    seconds = entry.get("seconds", 0) or 0

    if text in COMMON_HALLUCINATIONS and no_speech > 0.5:
        return "stock phrase Whisper falls back on when there is no speech"
    if no_speech > 0.6:
        return f"the model itself rates this as non-speech (no_speech_prob={no_speech:.2f})"
    if seconds > 3 and len(entry.get("text", "")) / max(seconds, 1) < 2.0:
        return "very little text for how long the file runs"
    return ""


def build(entries: list[dict], out: Path, only_font: str | None) -> tuple[int, int, int]:
    by_font: dict[str, list[dict]] = defaultdict(list)
    for entry in entries:
        if not (entry.get("is_speech") and entry.get("text")):
            continue
        if only_font and entry["font"].lower() != only_font.lower():
            continue
        by_font[entry["font"]].append(entry)

    spoken = sum(len(v) for v in by_font.values())
    flagged = sum(1 for v in by_font.values() for e in v if suspect_reason(e))

    lines = [
        "# What the sound fonts actually say",
        "",
        "> Generated by `tools/report.py` from Whisper transcriptions.",
        "> Do not edit by hand - regenerating overwrites this file.",
        "",
        f"**{spoken} spoken lines** across **{len(by_font)} fonts** "
        f"(scanned {len(entries)} files).",
        "",
    ]

    if flagged:
        noun = "entry is" if flagged == 1 else "entries are"
        lines += [
            f"⚠️ **{flagged} {noun} marked `?`** - the transcription may be invented. "
            "Flagged does not mean wrong: unusual but real speech gets marked too. "
            "Listen before relying on those.",
            "",
        ]

    lines += [
        "Find a specific line:",
        "",
        "```bash",
        'python tools/search.py "hello there"',
        "```",
        "",
    ]

    for font in sorted(by_font, key=str.lower):
        rows = sorted(by_font[font], key=lambda e: e["file"])
        lines += [f"## {font}", "", "| File | Sec | ? | Line |", "|---|---:|:-:|---|"]
        for entry in rows:
            mark = "⚠️" if suspect_reason(entry) else ""
            text = (entry.get("text") or "").replace("|", "\\|").strip()
            lines.append(
                f"| `{entry['file']}` | {entry.get('seconds', 0):.1f} | {mark} | {text} |"
            )
        lines.append("")

    out.write_text("\n".join(lines), "utf-8")
    return spoken, len(by_font), flagged


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Write the transcribed library out as a readable list.")
    ap.add_argument("--library", default="sound-library.json")
    ap.add_argument("--out", default="sound-library.md")
    ap.add_argument("--font", default=None, help="limit to one font")
    args = ap.parse_args()

    library = Path(args.library)
    if not library.exists():
        print(f"No library at {library}.", file=sys.stderr)
        print("Build one first:  python tools/transcribe.py --source E:/",
              file=sys.stderr)
        return 1

    entries = json.loads(library.read_text("utf-8"))
    out = Path(args.out)
    spoken, fonts, flagged = build(entries, out, args.font)

    if not spoken:
        print("No spoken lines matched - nothing written.", file=sys.stderr)
        return 1

    print(f"{out}  --  {spoken} lines across {fonts} fonts"
          + (f", {flagged} marked for a listen" if flagged else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
